data <- read.table("household_power_consumption.txt",sep=";",header=T)
subdata <- data[data$Date=="1/2/2007" | data$Date=="2/2/2007",]
metering1 <- as.double(as.character(subdata$Sub_metering_1))
metering2 <- as.double(as.character(subdata$Sub_metering_2))
metering3 <- as.double(as.character(subdata$Sub_metering_3))
date <- as.character(subdata$Date)
time <- as.character(subdata$Time)
datatime <- strptime(paste(date,time), "%d/%m/%Y %H:%M:%S")
png(file="plot3.png",width=480,height=480,units="px")
plot(datatime, metering1,type = "s",xlab = "",ylab = "Energy sub metering")
points(datatime, metering2,type = "s",col="red")
points(datatime, metering3,type = "s",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.9,lty=1,col = c("black","red","blue"))
dev.off()