data <- read.table("household_power_consumption.txt",sep=";",header=T)
subdata <- data[data$Date=="1/2/2007" | data$Date=="2/2/2007",]
apower <- as.double(as.character(subdata$Global_active_power))
voltage <- as.double(as.character(subdata$Voltage))
reapower <- as.double(as.character(subdata$Global_reactive_power))
metering1 <- as.double(as.character(subdata$Sub_metering_1))
metering2 <- as.double(as.character(subdata$Sub_metering_2))
metering3 <- as.double(as.character(subdata$Sub_metering_3))
date <- as.character(subdata$Date)
time <- as.character(subdata$Time)
datatime <- strptime(paste(date,time), "%d/%m/%Y %H:%M:%S")
png(file="plot4.png",width=480,height=480,units="px")
par(mfrow=c(2,2))
plot(datatime, apower,type = "s",xlab = "",ylab = "Global Active Power")
plot(datatime, voltage,type = "s",xlab = "datetime",ylab = "Voltage")
plot(datatime, metering1,type = "s",xlab = "",ylab = "Energy sub metering")
points(datatime, metering2,type = "s",col="red")
points(datatime, metering3,type = "s",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.9,lty=1,bty="n",col = c("black","red","blue"))
plot(datatime, reapower,type = "s",xlab = "datetime",ylab = "Global_reactive_power")
dev.off()